- hosts: jumpbox
  roles:
    - osp_create_network
    - osp_create_security
    - osp_flavor
  tasks:
  - name: Create frontend instance
    include_role:
       name: osp_create_instance
       vars_from: frontend.yml
  - name: Create app1 instance
    include_role:
       name: osp_create_instance
       vars_from: app1.yml
  - name: Create app2 instance
    include_role:
       name: osp_create_instance
       vars_from: app2.yml
  - name: Create db instance
    include_role:
       name: osp_create_instance
       vars_from: db.yml
  - name: Create dynamic inventory
    include_role:
       name: osp_create_inventry
