   - name: delete a server instance
     os_server:
       cloud: ospcloud
       name: "{{ item }}"
       key_name: ansible_ssh
       state: absent
     with_items:
       - [ app1, app2, db, frontend ]
